### ISSUE TITLE
Decupar erros e melhorias identificadas na sabatina da SEUSO e criar issues

### ISSUE THREAD

**Issue by arthurcordeiro** [lexml/editor-emendas#100]
https://easyretro.io/publicboard/F1CleoTjeYb50LQUD984JQgGR2Z2/3f1ca6fa-df8f-487e-813c-fd8e76cd1fd8

<img width="1440" alt="Captura de Tela 2022-10-21 às 11 28 07" src="https://user-images.githubusercontent.com/1903603/197259046-c80bc704-d45b-4edf-b277-f35b871b0d99.png">

**Comment by eurobertacs** [comment]
Boa tarde

Fiz uma análise preliminar e compartilho anexo com a descrição da sugestão dos colaboradores e uma descrição dessa análise.

Conversei com o Arthur e me coloquei à disposição para esclarecimentos.

[Análise do documento da Seuso.docx](https://github.com/lexml/editor-emendas/files/9912624/Analise.do.documento.da.Seuso.docx)
