### ISSUE TITLE
Pesquisa de texto para emendamento

### ISSUE THREAD

**Issue by fragomeni** [lexml/editor-emendas#11]
Depende de #7

Implementar a pesquisa feita no componente de seleção de texto para emendamento. "Dar vida ao componente".

Habilitar o botão "Selecionar" apenas se houver um texto selecionado.

Apontar inicialmente para o mesmo serviço usado pelo lexml-eta-vue.

**Comment by robsonbarrosdf** [comment]
Falta apontar para serviço "oficial" (Java)
