### ISSUE TITLE
Apresentar benefício e link do quadro de emendas na landing page

### ISSUE THREAD

**Issue by fragomeni** [lexml/editor-emendas#113]
Depende de definição da URL do quadro de emendas e da implantação em produção.

**Comment by arthurcordeiro** [comment]
https://github.com/lexml/editor-emendas/commit/1518dbfd965c43368c19db99f574ba0213afdaee

![Image](https://user-images.githubusercontent.com/1903603/205117309-b0fbe536-62c7-4b99-9525-72297b663cca.png)
