### ISSUE TITLE
Levantar estatísticas sobre a adequação da versão atual do editor às emendas recentes a MPs

### ISSUE THREAD

**Issue by fragomeni** [lexml/editor-emendas#115]
[Especificação ainda incompleta]

Avaliar um estoque recente de emendas a MP de modo a identificar:

- Quantidade total de emendas avaliadas;
- Quantidade de emendas que seriam atendidas pela versão atual do editor;
- Separar emendas que não seriam atendidas pela versão atual do editor agrupando pelo motivo e quantificar por motivo.
- Desconsiderar as Emendas orçamentárias pois não são tratadas pela Conle.

Antes de iniciar:

- Definir junto à equipe de negócio o critério de seleção das emendas a serem avaliadas;
- Verificar melhor forma de acessar essas emendas.

O que o editor faz:
- ...

O que o editor não faz (lista não exaustiva):
- ...

**Comment by eurobertacs** [comment]
Robson fez uma consulta prévia de MPVs e compartilhou.

[MPVs.xlsx](https://github.com/lexml/editor-emendas/files/10093470/MPVs.xlsx)

**Comment by eurobertacs** [comment]
Resumo das principais ações:

1. Criação da pasta compartilhada (Google Drive) para conter os produtos do levantamento e as Emendas criadas pelo Editor.
2. Criação do arquivo para conter a avaliação das emendas das MPVs de 2022. O arquivo já está disponível na pasta compartilhada.
3. Início do levantamento e análise das Emendas das MPVs de 2022.
4. Alterações no arquivo de avaliação das emendas das MPVs de 2022 para contemplar dashboard de informações coletadas a partir das informações deste levantamento.

Entregáveis

- Pasta compartilhada no Google: https://drive.google.com/drive/folders/1LqIA18tG1UyXpLwDs0SwX2zCfvRrdX_f?usp=sharing
- Arquivo com as informações das emendas avaliadas:

**Comment by eurobertacs** [comment]
Na daily do dia 30/11/2022, Fragomeni e Robson sugeriram que durante a análise das Emendas:

- Dispositivos que citam alterações na norma, verificar na norma publicada se os mesmos são novos ou existentes.
- Identificar Emendas que não seguem a N95.

**Comment by eurobertacs** [comment]
No mesmo dia 30/11/2022, recebi o e-mail do Leonardo da Conle com a indicação de MPVs que foram utilizadas para a elaboração do Quadro de Emendas. São elas: MPV 1051, MPV 1050, MPV 1063, MPV 1065, MPV 1069, MPV 1117, MPV 1121 e MPV 1133

[Quadros de Emendas - E-mail do Leonardo da Conle.pdf](https://github.com/lexml/editor-emendas/files/10158514/Quadros.de.Emendas.-.E-mail.do.Leonardo.da.Conle.pdf)
[Quadros_de_Emendas.zip](https://github.com/lexml/editor-emendas/files/10158513/Quadros_de_Emendas.zip)

**Comment by eurobertacs** [comment]
Síntese da análise da **MPV 1141/2022**:

- 4 Emendas
- Ausência do recurso tab no campo justificativa para incluir trechos que justifiquem a necessidade de alteração na MPV.

**Comment by eurobertacs** [comment]
Síntese da análise da **MPV 1140/2022**:

- 19 Emendas

Problemas identificados:
- A

**Comment by eurobertacs** [comment]
Síntese da análise da **MPV 1121/2022**:
- 24 Emendas.
- Localização dos arquivos gerados: https://drive.google.com/drive/folders/1jnJbDgCKbGZ9uqIdKK561kkyW-kHu4mN?usp=sharing

**Problemas identificados:**

**Comment by eurobertacs** [comment]
Síntese da análise da **MPV 1133/2022**:
-  Emendas.
- Localização dos arquivos gerados: 

**Problemas identificados:**
-

**Comment by eurobertacs** [comment]
Síntese da análise da **MPV 1117/2022**:
-  25 Emendas.
- Localização dos arquivos gerados: 
- Link da planilha atualizada: https://docs.google.com/spreadsheets/d/1qUUzNGK6E6MiH2Wn-aUN_wV7a08KqXNR/edit?usp=share_link&ouid=108759321449410735647&rtpof=true&sd=true

**Problemas identificados:**

**Comment by eurobertacs** [comment]
Síntese da análise da **MPV 1069/2021 (Em andamento)**:
-  64 Emendas.
- 43 Emendas analisadas.
- Localização dos arquivos gerados: https://drive.google.com/drive/folders/1BPqYaznHwtE48wbe0bFEuwSJtapkikzW?usp=sharing
- Link da planilha atualizada: https://docs.google.com/spreadsheets/d/1qUUzNGK6E6MiH2Wn-aUN_wV7a08KqXNR/edit?usp=share_link&ouid=108759321449410735647&rtpof=true&sd=true

**Problemas identificados:**
- Parágrafo inexistente na norma foi criado para incluir novos incisos.
- Sem funcionalidade para suprimir dispositivo de norma alterada.
- Usuário informou alínea após o artigo.
- Usuário informou dispositivo errado para inclusão.
- Alteração de norma que não segue N95.
-

**Comment by eurobertacs** [comment]
Na daily de 01/02/2023, Fragomeni solicitou um relatório com o resumo dos resultados obtidos com o levantamento. As informações do relatório serão utilizados para apresentar à Dileg e Conle na cerimônia do dia 06/02/2023.

Segue anexo para análise: 

[Relatório de resultados do levantamento de uso do Editor de Emendas.docx](https://github.com/lexml/editor-emendas/files/10574844/Relatorio.de.resultados.do.levantamento.de.uso.do.Editor.de.Emendas.docx)

**Comment by eurobertacs** [comment]
No dia 03/02/2023 foi realizada uma reunião com o Fragomeni, Arthur e Cenira para esclarecer dúvidas e obter feedback do relatório de resultados do levantamento do uso do Editor.

Com isso, os produtos abaixo foram ajustados:

- [Relatório de resultados do levantamento de uso do Editor de Emendas-v2.docx](https://github.com/lexml/editor-emendas/files/10614054/Relatorio.de.resultados.do.levantamento.de.uso.do.Editor.de.Emendas-v2.docx)
- [Exemplos.txt](https://github.com/lexml/editor-emendas/files/10614059/Exemplos.txt)
- Link da planilha atualizada: https://docs.google.com/spreadsheets/d/1qUUzNGK6E6MiH2Wn-aUN_wV7a08KqXNR/edit#gid=292277244

**Comment by fragomeni** [comment]
O trabalho será continuado em #150
