### ISSUE TITLE
Usar cabeçalho e rodapé padrão do site do Congresso Nacional na landing page

### ISSUE THREAD

**Issue by fragomeni** [lexml/editor-emendas#118]
Será utilizado o modelo da página https://www6g.senado.leg.br/busca-congresso/?q=

O modelo está no arquivo abaixo:

[tema-congresso-app.zip](https://github.com/lexml/editor-emendas/files/10228018/tema-congresso-app.zip)

**Comment by arthurcordeiro** [comment]
https://github.com/lexml/editor-emendas/commit/4b7c7ac78f4931fd0d5394c92619805226174767

![Image](https://user-images.githubusercontent.com/1903603/208117582-6e0de072-eae1-4184-88ed-2cfab68bd297.png)
![Image](https://user-images.githubusercontent.com/1903603/208117581-411fdc34-387b-4481-92d3-2147e0fdb8c1.png)
![Image](https://user-images.githubusercontent.com/1903603/208117803-b472dbb1-9eab-4eed-a7e0-8903618e25c4.png)
