### ISSUE TITLE
Abrir modo de edição padrão após seleção de texto para emendamento

### ISSUE THREAD

**Issue by fragomeni** [lexml/editor-emendas#12]
Depende de #8  e #11. Levar em consideração https://github.com/lexml/lexml-eta/issues/398

Abrir texto para emendamento para nova emenda após usuário selecionar o texto.

![image](https://user-images.githubusercontent.com/5323676/184735843-6e035f70-3979-43ad-98b9-ba203376ffb4.png)

![image](https://user-images.githubusercontent.com/5323676/184735860-67e4527e-5188-43f2-9ad4-045924f4dfec.png)

Usar como nome da emenda "Emenda à MPV número/ano".

![image](https://user-images.githubusercontent.com/5323676/184991009-29fd24ef-2560-41dc-9b97-115bd902920c.png)

**Comment by arthurcordeiro** [comment]
https://github.com/lexml/editor-emendas/commit/5336325377e015e2e9963dd8d6b34619becf1b10

https://github.com/lexml/editor-emendas/commit/dcafd05253c3e54266e56931561219f2135fd064
