### ISSUE TITLE
Especificar vídeos e texto de ajuda para a funcionalidade de colar dispositivos da MP, em alteração de norma e em artigo onde couber.

### ISSUE THREAD

**Issue by fragomeni** [lexml/editor-emendas#127]
Vídeo 1: Colar dispositivos (introdução)
- Informar que é possível colar vários dispositivos a partir de texto da Web, Word ou PDF.
- O PDF apresenta mais dificuldades. Dar preferência ao Word.
- Isso é útil quando se deseja reproduzir no editor de emendas uma emenda já existente ou quando se deseja adicionar à emenda dispositivos de um projeto de lei.
- É possível colar um ou mais dispositivos do mesmo tipo no nível de artigo ou dispositivos de artigo com dispositivos subordinados.
- Quando são identificados dispositivos com a mesma numeração já existentes na proposição, o usuário pode optar por alterar os dispositivos existentes com a mesma numeração ou adicionar dispositivos.
  - Mostrar o resultado das duas opções (adicionando e alterando sobre dispositivo da MP).
  - Utilizar como exemplo dois artigos com dispositivos subordinados e omissis, sem alteração de norma.
- Dispositivos adicionados são posicionados após o dispositivo atual.
- É muito importante a verificação do texto que foi colado para confirmar se está de acordo com a sua intenção. Pode ocorrer do texto colado necessitar de ajustes para ficar fiel à origem.
- Recomendar assistir aos vídeos 2 e 3 e ler a lista de restrições.

Vídeo 2: Colar dispositivos (boas práticas)
- Para que a colagem funcione é necessário que os dispositivos copiados estejam de acordo com a LCP 95/98.
  - Ou seja, sigam a estrutura hierárquica (artigo, parágrafos, incisos, alíneas e itens) e respeitem as convenções de rótulo e numeração.
  - Por exemplo, o editor não irá aceitar a colagem de artigos com alíneas sem incisos.
- Colar de PDF
  - Apesar de muitas vezes funcionar colar diretamente do PDF, recomenda-se colar no Word, conferir e fazer eventuais correções no texto e depois copiar e colar a partir do texto do Word. (Verificar se é melhor colar no Word ou abrir o PDF no Word)
  - Apresentar um exemplo.
- Orientações sobre aspas
  - Mostrar que é possível copiar artigos com ou sem aspas com exceção de artigos que contenham alteração de norma, nesse caso, as aspas do artigo não devem ser copiadas.
    - Mostrar os casos

Vídeo 3: Colar dispositivos (uso de omissis)
- Falar que o comportamento da colagem pode variar caso o texto colado possua ou não omissis.
- Apresentar exemplos:
  - ao colar novos dispositivos da proposição, os omissis são ignorados e os dispositivos são renumerados;
  - ao colar novos dispositivos de norma alterada, os omissis são adicionados ao texto;
  - ao alterar dispositivos existentes na proposição ou em norma alterada
   - os omisis indicam que devem ser alterados apenas os dispositivos subordinados sem fazer renumeração, a não existência de omissis ao final de uma lista de dispositivos subordinados é considerada como supressão dos dispositivos não constantes no texto colado;
   - se essas supressões não forem desejadas, é possível desfazê-las manualmente.
   - caso o texto não possua omissis, é considerado que o usuário deseja substituir todo o conteúdo do dispositivo pelo conteúdo colado. Isso implica na supressão de dispositivos subordinados que não existam no texto colado.

Apresentar restrições em ajuda de texto:
- Restrições:
  - Não é suportada a colagem de agrupadores de artigo (título, capítulo, seção etc)
  - Não é permitida a colagem de uma lista de dispositivos de tipos diferentes (ex: incisos seguidos de artigos)
  - A técnica legislativa dispositivos copiados deve estar correta, de acordo com a LCP 95/98. Por exemplo: não serão aceitas alíneas sem incisos, itens sem alíneas etc.
  - Não podem ser colados dispositivos com rótulos duplicados (ex: dois artigos com o mesmo número)
  - Só é permitido colar dispositivos em posição coerente com o seu tipo (ex: não é permitido colar alíneas sobre parágrafos)
  - Não é permitido colar artigo não numerado em alteração de norma
  - Não é permitido colar artigo com alteração de norma dentro de uma alteração de norma.
  - Não é permitido colar dispositivos subordinados a dispositivos suprimidos (ex: colar um parágrafo em um artigo suprimido)
  - Não é possível colar modificando um dispositivo que já está modificado.

**Comment by eurobertacs** [comment]
Aguardar retorno do João Holanda para definir o que documentar sobre o recurso de colar dispositivos.

Ao longo da execução do ticket #115, identifiquei comportamentos diferentes ao utilizar o recurso colar.
