### ISSUE TITLE
Editar o vídeo de introdução ao Editor de Emendas regravado pelo João

### ISSUE THREAD

**Issue by eurobertacs** [lexml/editor-emendas#128]
Link dos vídeos produzidos pelo João Holanda:

- Vídeo 1: https://www.vidline.com/share/V00R6HMWBE/c57d281fbbec7ad7aed94945b80e6828?n=
- Vídeo 2: https://www.vidline.com/share/V07MBHAK1M/b858c8f3baf93116ec78fcb1c0f7d46a?n=

**Comment by eurobertacs** [comment]
Link do vídeo editado está disponível no endereço https://drive.google.com/file/d/1smdUQ4kFWdmVNhz6ICilr9YDmq-KfqyZ/view?usp=share_link

**Comment by arthurcordeiro** [comment]
feat: Legendar o vídeo de introdução ao Editor de Emendas regravado pelo João e atualizar Ajuda

https://github.com/lexml/editor-emendas/commit/d776ad0b16a3886ebf9a8d5d7c48a2de30e7647f
