### ISSUE TITLE
O campo Justificativa poderia conter a opção de inserir notas de rodapé

### ISSUE THREAD

**Issue by eurobertacs** [lexml/editor-emendas#131]
Ao longo da análise das emendas das MP's, identifiquei algumas que contém na justificativa notas de rodapé com a informações sobre o termo referenciado.

Seguem alguns exemplos de Emendas:

- Emenda 002  da MPV 1141/2022: https://legis.senado.leg.br/sdleg-getter/documento?dm=9214559&ts=1669301095162&disposition=inline&ts=1669301095162
- Emenda 002 da MPV 1121/2022: https://legis.senado.leg.br/sdleg-getter/documento?dm=9169791&ts=1666796449191&disposition=inline&ts=1666796449191
- Emenda 003 da MPV 1121/2022: https://legis.senado.leg.br/sdleg-getter/documento?dm=9170029&ts=1666796449204&disposition=inline&ts=1666796449204

___________________________________________
Conforme alinhado com o Fragomeni, 28/09/2023:
Grupo: Notas de rodapé
Prioridade: Média
Esforço: G

**Comment by arthurcordeiro** [comment]
feat: cria modal de notas de rodapé
https://github.com/lexml/lexml-eta/commit/a8b3da2c2198a75cfceb52d53bd00a44e8d15256

feat: converte modal nota de rodapé para shadow root e remove listeners ao fechar
https://github.com/lexml/lexml-eta/commit/e428590bca0da781fa6e752afb450b122d87222a

![Image](https://github.com/lexml/editor-emendas/assets/1903603/1576ef01-ffd2-4356-b4f1-17a0c2854978)

**Comment by arthurcordeiro** [comment]
feat: cria estilo de nota de rodapé para o conteúdo da aba Notas
https://github.com/lexml/lexml-eta/commit/e13884384cc350a2beb2ab190442cfb03b561d95

![Image](https://github.com/lexml/editor-emendas/assets/1903603/7e3d49d9-b48e-40fc-aa0f-f56a97ba2088)

**Comment by arthurcordeiro** [comment]
feat/ux: cria efeito pulsar e ativa/desativa localização das notas de rodapé 
https://github.com/lexml/lexml-eta/commit/0bfddabe941151511e2f09c3289152bf11fee801
