### ISSUE TITLE
Editor identifica modificação ao clicar em dispositivo original contendo aspas retas.

### ISSUE THREAD

**Issue by fragomeni** [lexml/editor-emendas#135]
Ao clicar em dispositivo original com aspas retas o editor converte as aspas curvas e identifica o dispositivo como modificado e não tem como desfazer.

Este problema já havia sido resolvido no tíquete https://github.com/lexml/lexml-eta/issues/323 do lexml-eta já transformando as aspas retas em curvas na abertura do arquivo, mas apareceu novamente no editor-emendas. Provavelmente a correção foi feita na aplicação demo em vez de ter sido feita no componente.

Para reproduzir na MP 1159

![image](https://user-images.githubusercontent.com/5323676/213821048-a69765b0-fb9a-4630-8c88-fbec54379da9.png)

Clicar e sair do inciso XII

![image](https://user-images.githubusercontent.com/5323676/213821173-63741dd0-782e-4d0f-858c-7ac5f7016901.png)

Não houve modificação do dispositivo pelo usuário, portanto não deveria ter sido identificada a alteração.

**Comment by arthurcordeiro** [comment]
feat: cria função que troca aspas retas por aspas curvas apenas no innerHtml dos elementos do texto

https://github.com/lexml/lexml-eta/commit/2bd8daf8dac24f3f247ce2238005f8abf3651f2e
