### ISSUE TITLE
Apresentar versão da aplicação na landing page e na tela de edição

### ISSUE THREAD

**Issue by fragomeni** [lexml/editor-emendas#148]
@arthurcordeiro, definir local e layout.

@DennysMarinho, fazer um serviço que busque a versão da aplicação java, chamar o serviço na carga da aplicação e apresentar na tela.

**Comment by arthurcordeiro** [comment]
https://github.com/lexml/editor-emendas/commit/6a16bbcb4044b98e99063709ea0a66435cb1a76f

![Image](https://user-images.githubusercontent.com/1903603/224194745-76067c73-c2be-4cb8-a14e-2cdc2a12fd39.png)

![Image](https://user-images.githubusercontent.com/1903603/224194746-5ed80cc1-eb52-4153-8469-03e4a81413ae.png)
