### ISSUE TITLE
UX Research

### ISSUE THREAD

**Issue by kailinerocha** [lexml/editor-emendas#150]

**Comment by kailinerocha** [comment]
Hoje, dia 07/03, foi feita uma reunião com o Arthur e Roberta às 11h30 para apresentação do PDF em anexo acima. O objetivo da reunião foi para pedir orientações e validar os objetivos da pesquisa bem como as perguntas do questionário.

Alguns pontos discutidos em reunião:

    - O objetivo número 1 (validar os dados da pesquisa anterior) que se encontra na página 5 do PDF, por sugestão do Arthur deve-ser trocar a ordem de importância e deixar como último objetivo da pesquisa.

    - O objetivo número 2 (Descobrir quem são os usuários ativos do Editor) que se encontra na mesma página citada acima, por sugestão do Arthur deve-se trocar para "Descobrir quem faz a elaboração das emendas".

    - O objetivo número 3 (Qual a motivação do uso frequente da funcionalidade “onde couber”), por sugestão da Roberta deve-se trocar para "Descobrir qual a motivação para elaborar emendas com o onde couber".

    - O Arthur também sugeriu em dividir a pesquisa em duas partes. Uma com o objetivo de descobrir quem são as pessoas que elaboram emendas e outra pesquisa com o objetivo de identificar melhorias técnicas/visuais no Editor.

    - Por fim, também foi discutido que as perguntas do questionário precisam de alguns ajustes. Enviei o PDF do questionário para o Arthur e para a Roberta para que eles possam contribuir com as modificações.

Segue em anexo o PDF com o questionário. São dois questionários, um que se aplica ao cenário em que os usuários já utilizam o Editor e outro que se aplica ao cenário dos usuários que não usam ou não conhecem o Editor.



[Cenário de quem não usa o Editor - Roteiro de Entrevista.pdf](https://github.com/lexml/editor-emendas/files/10913414/Cenario.de.quem.nao.usa.o.Editor.-.Roteiro.de.Entrevista.pdf)
[Cenário de quem já usa o Editor - Roteiro entrevista.pdf](https://github.com/lexml/editor-emendas/files/10913413/Cenario.de.quem.ja.usa.o.Editor.-.Roteiro.entrevista.pdf)



@eurobertacs @arthurcordeiro @robsonbarrosdf @fragomeni

**Comment by arthurcordeiro** [comment]
Oi @kailinerocha, tá ficando muito bom.

Será que cabem umas perguntas que ajude-nos a descobrir quem são os "editores de emenda" lá na origem? É algo sensível ou privativo? Tipo:
 
- Você que redige as emendas? E a justificativa?
- Acontece de receber pronta a emenda/justificativa e apenas revisar e encaminhar? 
- Se sim, quais são as origens mais comuns?
(  ) Parlamentares
(  ) Comissões
(  ) Partidos políticos
(  ) Entidades da sociedade civil
(  ) Cidadãos

Fiz umas observações de quais ferramentas são utilizadas na elaboração de emendas atualmente.

[Cenário de quem já usa o Editor - Roteiro entrevista.pdf](https://github.com/lexml/editor-emendas/files/10922132/Cenario.de.quem.ja.usa.o.Editor.-.Roteiro.entrevista.pdf)
[Cenário de quem não usa o Editor - Roteiro de Entrevista.pdf](https://github.com/lexml/editor-emendas/files/10922131/Cenario.de.quem.nao.usa.o.Editor.-.Roteiro.de.Entrevista.pdf)

**Comment by eurobertacs** [comment]
@kailinerocha, está excelente o questionário!

As observações que vou listar são complementações para seu trabalho.

Anexo **Cenário de quem já usa o Editor**

Na **questão 13**, recomendo obter a lista completa das funcionalidades a partir do próprio Editor. As que identifiquei são algumas. Sugiro ver com o Fragomeni ou o Robson a possibilidade de obter a lista completa.

Anexo **Cenário de quem não utiliza o Editor**

Sugiro que o item **Objetivos gerais** possa ter o enfoque para o usuário que elabora emendas sem o uso do Editor. Segue uma sugestão de texto:

_Compreender as necessidades dos usuários que elaboram Emendas para Medidas Provisórias ao longo do processo legislativo._

Sugiro que o item **Objetivos específicos** possa ter o enfoque para o usuário que elabora emendas sem o uso do Editor. Segue uma sugestão de textos:

_1. Descobrir os usuários que elaboram Emendas para Medidas Provisórias na Câmara dos Deputados.
2. Descobrir as ferramentas utilizadas pelos usuários.
3. Descobrir quais os problemas/erros mais comununs ao elaborar Emendas.
4. Descobrir qual motivação do uso de Emendas Onde Couber.
5. Descobrir se os usuários conhecem o Editor de Emendas._

Sugiro que o item **Introdução** possa ter o enfoque para o usuário que elabora emendas sem o uso do Editor. Segue uma sugestão de texto:

_Olá!Nós somos da equipe de desenvolvimento do Editor de Emendas e estamos buscando ouvir os nossos usuários que elaboram Emendas para identificar como é feita as Emendas e se tem ciência sobre o Editor de Emendas._

_Durante o questionário, faremos algumas perguntas sobre a sua experiência com elaboração de Emendas e também alguns dados quantitativos como idade e cargo ocupado apenas para melhor compreendimento de quem são os usuários._

Sugiro que a **Questão 11** possa ter o enfoque para o usuário que elabora emendas sem o uso do Editor. Segue uma sugestão de texto:

_Você já elaborou emendas onde couber na ferramenta mencionada?_

Sugiro que a **Questão 12** possa ter o enfoque para o usuário que elabora emendas sem o uso do Editor. Segue uma sugestão de texto:

_Você entende a finalidade da emenda onde couber? Se sim, poderia nos explicar?_

Espero ter ajudado!

**Comment by kailinerocha** [comment]
Agradeço a @eurobertacs e ao @arthurcordeiro pelas sugestões valiosas que contribuíram para o aprimoramento do questionário.

Após a coleta de sugestões, segue a versão refinada do questionário. Ele pode ser aplicado imediatamente e aberto ao público. O tempo médio de conclusão é de 5 a 10 minutos.

Para manter o foco da pesquisa, os usuários que responderem "não" à pergunta 4 terão o questionário encerrado e receberão nosso agradecimento pela participação.



[Questionário Refinado.pdf](https://github.com/lexml/editor-emendas/files/10979593/Questionario.Refinado.pdf)

@robsonbarrosdf @fragomeni
