### ISSUE TITLE
Investigar erros no uso em dispositivos móveis (fazer um levantamento)

### ISSUE THREAD

**Issue by eurobertacs** [lexml/editor-emendas#151]
A usuária da Câmara dos Deputados, Jackeline Pires Silva, relatou por meio do formulário do Editor de Emendas não acessar o sistema pelo dispositivo Galaxy Tab A, versão 5.0.2 do Android. Segue descrição da usuária:

_Reporto que o site https://www3.congressonacional.leg.br/editor-emendas/ não está abrindo no dispositivo Galaxy Tab A, versão 5.0.2 do Android_

Segue anexo do e-mail recebido pela caixa do editoremenda@camara.leg.br

[Contato do site - Editor de Emendas-Jackeline Pires-15-03-2023.pdf](https://github.com/lexml/editor-emendas/files/10984772/Contato.do.site.-.Editor.de.Emendas-Jackeline.Pires-15-03-2023.pdf)

___________________________________________
Conforme alinhado com o Fragomeni, 28/09/2023:
Grupo: 
Prioridade: Alta
Esforço: G

**Comment by arthurcordeiro** [comment]
https://docs.google.com/document/d/11LzL1IkRw3fze2ibD0goEhL2YOMZ3SzzD3k8ZL68VIo/edit?usp=sharing
