### ISSUE TITLE
Teste de usabilidade

### ISSUE THREAD

**Issue by kailinerocha** [lexml/editor-emendas#159]

**Comment by kailinerocha** [comment]
31/03 - Estrutura do teste

O teste de usabilidade envolve observar os usuários enquanto eles executam tarefas no seu produto.

Sobre definições do teste:

 - Definir objetivo do teste.
 - Recrutar usuários que tenham características específicas para o objetivo do cliente. 5 perfis diferentes, sendo pelo menos um usuário com alguma deficiência (visual ou outra), a fim de avaliar a usabilidade do produto em termos de acessibilidade.
 - Definir se o teste será presencial ou remoto.
 - Definir quais tarefas serão testadas.

Sobre a realização do teste:
 - Será necessário um facilitador de teste. Ele realizará o teste por meio de um protocolo de perguntas e observações psicológicas de reações. (Kailine e Roberta)
 - Seleção de alguns observadores para assistir a realização do teste na mesma sala ou em uma sala separada. Os observadores serão responsáveis por anotar insights, erros, pontos de frustrações e perguntas extras para o facilitador utilizar no final do teste.
 - Verificar possibilidade de algum tipo de incentivo para os usuários participarem do teste. 
 - O ambiente do teste precisa ser acolhedor, é recomendado deixar água ou café disponível para que o usuário se sinta confortável. É importante mencionar que o usuário pode pausar o teste caso precise e principalmente informar que o que está sendo testado é o produto e não ele. 
 - O ambiente precisa ter pelo menos duas cadeiras, uma para o usuário e uma para o facilitador, um computador, uma webcam, os cards com as tarefas a serem executadas.  É recomendado que os observadores fiquem atrás do usuário e do facilitador apenas anotando o que for preciso.
 - Antes de iniciar o teste é importante que o facilitador explique o contexto para o usuário, peça autorização para gravação do teste com assinatura do formulário e se deixe a disposição para qualquer dúvida que o usuário possa ter.
 - Planeje as sessões de teste, estimando tempo para: instruções; execução do teste, e respostas de um questionário. Faça uma entrevista pós-teste, utilize uma média de 30 minutos por teste.

**Comment by kailinerocha** [comment]
31/03 - Entrega

 - Estudo da estrutura
 - Template de consentimento
 - Roteiro de teste de usabilidade


[Estudo da estrutura.pdf](https://github.com/lexml/editor-emendas/files/11124247/Estudo.da.estrutura.pdf)
[Roteiro do teste.pdf](https://github.com/lexml/editor-emendas/files/11124249/Roteiro.do.teste.pdf)
[Formulário de consentimento.pdf](https://github.com/lexml/editor-emendas/files/11124248/Formulario.de.consentimento.pdf)

**Comment by kailinerocha** [comment]
10/04 - Entrega

Tarefas do teste de usabilidade.

[Tarefas do teste.pdf](https://github.com/lexml/editor-emendas/files/11205767/Tarefas.do.teste.pdf)

@arthurcordeiro e @eurobertacs poderiam dar uma olhada e ver o que acham?

**Comment by kailinerocha** [comment]
12/04 - Entrega

Conforme discutido na daily, segue tarefas do teste de usabilidade com ajustes solicitados.

[Tarefas do teste.pdf](https://github.com/lexml/editor-emendas/files/11214646/Tarefas.do.teste.pdf)

@fragomeni @eurobertacs @arthurcordeiro

**Comment by kailinerocha** [comment]
02/05 - Entrega

Relatório de teste de usabilidade do usuário Luiz Beltrão - Consultor do Senado Federal - PCD com baixa visão.

Ao final do relatório, disponibilizamos um link para a gravação da tela do computador do usuário durante a execução do teste. No entanto, gostaríamos de informar que enfrentamos um problema técnico com a webcam, resultando na perda de áudio e reação do usuário. Portanto, temos apenas a gravação da tela do computador.



[Relatório teste de usabilidade - Luiz (PCD).pdf](https://github.com/lexml/editor-emendas/files/11374527/Relatorio.teste.de.usabilidade.-.Luiz.PCD.pdf)

@arthurcordeiro @fragomeni @robsonbarrosdf @eurobertacs

**Comment by arthurcordeiro** [comment]
Observações do teste realizado em 02.05.2023

- Entrevista:
	- Salvar roteiro em pdf para os links abrirem direto ao clicar.
	- Testar o visualizar e salvar antes da entrevista.

- Tela abrir MPV: 
	- Não descobriu em desmarcar o checkbox para encontrar filtros das proposições.

- Editor: 
	- Não viu o título do projeto. Sugeriu colocar no corpo do editor.
	- Título da página (Aba no navegador) não mostra a MPV. 
	- Alínea: Não pode filho único.
	- Dificuldade em encontrar artigo em MPs com muitos dispositivos. Não deduziu que poderia usar o próprio CTRL+F do Chrome.
	- Copiar e colar:
		- Colar Texto simples como default.
		- Colar a primeira vez demora pra mostrar modal sem tela de carregando.
	- Atalhos: Dificuldade em ver os atalhos. Procurou no menu Ajuda.

- Menu:
	- Não encontrou o botão salvar.
	- Não entendeu o que é "Wiki do projeto" no menu ajuda.

- Bugs:
	- Saiu do editor sem confirmação de fechar ou sair.
	- Visualizar e salvar não funcionaram.

- Curiosidade:
	- 'Emendas de plenário' com fluxo pelo whatsapp entre consultor, assessoria do plenário e assessoria do relator.

**Comment by kailinerocha** [comment]
04/05 - Entrega

Relatório de teste de usabilidade do usuário: Perfil - Usuário de liderança

Ao final do relatório, disponibilizamos um link para a gravação da tela do computador do usuário durante a execução do teste. 



[Relatório teste de usabilidade - Alessandra.pdf](https://github.com/lexml/editor-emendas/files/11401800/Relatorio.teste.de.usabilidade.-.Alessandra.pdf)

@fragomeni @arthurcordeiro @robsonbarrosdf @eurobertacs @ceniravecchi

**Comment by kailinerocha** [comment]
05/05 - Entrega

Relatório de teste de usabilidade do usuário: Perfil Consultor Câmara dos Deputados.

Ao final do relatório, disponibilizamos um link para a gravação da tela do computador do usuário durante a execução do teste.

[Teste de usabilidade - Claudionor Rocha.pdf](https://github.com/lexml/editor-emendas/files/11402895/Teste.de.usabilidade.-.Claudionor.Rocha.pdf)

@fragomeni @arthurcordeiro @robsonbarrosdf @eurobertacs @ceniravecchi

**Comment by kailinerocha** [comment]
08/05 - Entrega

Tabela com resultado geral do teste de usabilidade.

[resultado.pdf](https://github.com/lexml/editor-emendas/files/11422416/resultado.pdf)
