### ISSUE TITLE
Criar vídeo tutorial sobre adição de agrupadores de artigo

### ISSUE THREAD

**Issue by fragomeni** [lexml/editor-emendas#162]

**Comment by arthurcordeiro** [comment]
Proposta inicial de roteiro:

Bem-vindo a mais um tutorial do Editor de Emendas. Hoje, você aprenderá sobre uma função vital: os Agrupadores. Antes de avançarmos para as etapas práticas, é essencial entender o que são agrupadores na técnica legislativa. De acordo com a LCP 95/98, que estabelece normas para a elaboração de leis, os agrupadores são dispositivos que ajudam a organizar o conteúdo de forma hierárquica e clara. Eles se referem a divisões como artigos, parágrafos, incisos, alíneas e itens.

A organização hierárquica é vital para a compreensão e aplicação de qualquer norma. Sem uma estrutura clara, seria difícil localizar informações específicas ou entender o contexto geral. Os agrupadores são os pilares dessa estruturação.

Acesse o Editor de Emendas e, no menu lateral, clique em "Inserir Agrupador". Uma janela aparecerá com as opções: Artigo, Parágrafo, Inciso, Alínea e Item. Escolha o agrupador que deseja inserir. Lembre-se de que a estrutura deve ser respeitada: por exemplo, antes de adicionar alíneas, você precisa ter um inciso. Depois de selecionar o agrupador, um campo de texto aparecerá para você inserir o conteúdo desejado. Preencha com as informações relevantes e clique em "Salvar".

Se você perceber que inseriu um agrupador no local errado, não se preocupe. É possível reposicionar conforme necessário. Dominar a função de agrupadores no Editor de Emendas é fundamental para garantir que suas propostas estejam em conformidade com as normas de técnica legislativa. A prática leva à perfeição, então não hesite em experimentar e testar a ferramenta até que se sinta confortável.

Agradecemos por assistir a este tutorial. Em caso de dúvidas, consulte nossos outros materiais ou entre em contato conosco.

**Comment by fragomeni** [comment]
@arthurcordeiro, ficou muito bom. Vale só dar uma revisada nas legendas.

Seguem exemplos de erros:

Agrupar dores
![image](https://github.com/lexml/editor-emendas/assets/5323676/5ff93d95-3499-47ca-a485-75bac9a35e3f)
![image](https://github.com/lexml/editor-emendas/assets/5323676/28f9420e-5a4a-4ab4-b70f-ae22cf43acd5)


1176
![image](https://github.com/lexml/editor-emendas/assets/5323676/3554df7c-db93-4cbc-9319-136d9106faf9)

Selecioná-la
![image](https://github.com/lexml/editor-emendas/assets/5323676/ea24f03d-f0de-44c9-9fbd-d2fb08914be2)

**Comment by arthurcordeiro** [comment]
Vídeo e legendas corrigidas:

https://youtu.be/Mt1ppqAIsNk
