### ISSUE TITLE
Gravar vídeo 3 (uso de omissis) para a funcionalidade de colar dispositivos

### ISSUE THREAD

**Issue by fragomeni** [lexml/editor-emendas#174]
Ver #127 

O comportamento da colagem pode variar caso o texto colado possua ou não linhas pontilhadas.
Vamos apresentar alguns casos

**Caso 1: Adicionando dispositivos a uma norma alterada.**
As linhas pontilhadas serão coladas normalmente da forma que estavam no dispositivo copiado.

MPV 1199/23

Colar dentro da alteração da lei

Art. 3º ...............................................
.......................
§ 2º Constituem-se recursos próprios para os fins do disposto nesta Lei, inclusive os valores depositados ou mantidos em conta vinculada do trabalhador no Fundo de Garantia do Tempo de Serviço que, em decorrência de opção pela modalidade de que trata o inciso II do art. 20-A da Lei nº 8.036, de 11 maio de 1990, e do disposto no inciso II do § 2º do mesmo art. 20-A, e que não tenham sido objeto de saque pelo titular em razão de rescisão sem justa pelo empregador ocorrida até 3 de outubro de 2023.

**Caso 2: Alterando dispositivos (tanto já existentes na proposição quanto em norma alterada).**
Ao colar um dispositivo que vai alterar um dispositivo já existente na proposição, ou em uma alteração de norma, considera-se que as linhas pontilhadas representam dispositivos que não devem ser alterados. Nesse caso o editor ignora as linhas pontilhadas e altera apenas os dispositivos subordinados, sem renumerá-los.

Exemplo:

MPV 1176/23

Art. 7º ...............................................
§ 1º ...............................................
...............................................
II – valor de até R$ 15.000,00 (quinze mil reais) por devedor, considerado o somatório das dívidas financiadas, a ser definido em ato do Ministro de Estado da Fazenda.
...............................................

**Caso 2.1: A não existência de linha pontilhada ao final de uma lista de dispositivos subordinados é considerada como supressão dos dispositivos não existentes no texto colado.**
Se essas supressões não forem desejadas, é possível desfazê-las manualmente.

Exemplo:

MPV 1176/23

Art. 8º Poderão ser incluídas no Desenrola Brasil - Faixa 1 as dívidas de natureza privada, de pessoas físicas inscritas em cadastro de inadimplentes até a data de publicação desta Lei que:
I – tenham renda mensal igual ou inferior a três salários mínimos; ou

**Caso 3: Adicionando dispositivos com linha pontilhada à proposição, ou seja, fora de alteração de norma.**

Considerando que novos dispositivos propostos para a proposição não devem possuir linhas pontilhadas, o editor ignora as linhas pontilhadas e renumera os dispositivos adjacentes.

Exemplo:

MPV 1176/23

Art. 2º Texto do caput do novo artigo
......
§ 5º Texto do novo parágrafo

Observar que a linha pontilhada acima não faz sentido em um dispositivo novo.

___________________________________________
Conforme alinhado com o Fragomeni, 28/09/2023:
Grupo: 
Prioridade: Média
Esforço: M

**Comment by arthurcordeiro** [comment]
# Roteiro para Vídeo Tutorial - Editor de Emendas com Linhas Pontilhadas

## Introdução
- Apresentação do tema: Uso de linhas pontilhadas ao colar texto de emenda no editor.
- Breve descrição do propósito do tutorial.

## Contextualização
- Explicação sobre o funcionamento das linhas pontilhadas no editor de emendas.
- Destaque para a importância de entender como o editor lida com essas linhas.

## Casos de Uso

### Caso 1: Adicionando Dispositivos a uma Norma Alterada
- Demonstração prática de como colar dispositivos com linhas pontilhadas dentro de uma alteração de lei.
- Exemplo com MPV 1199/23.

### Caso 2: Alterando Dispositivos Existentes
- Explicação de como o editor trata linhas pontilhadas ao alterar dispositivos existentes na proposição ou em uma alteração de norma.
- Exemplo com MPV 1176/23.

### Caso 2.1: Supressão de Dispositivos
- Demonstração do tratamento de linhas pontilhadas como supressão de dispositivos não existentes no texto colado.
- Exemplo com MPV 1176/23.

### Caso 3: Adicionando Dispositivos à Proposição
- Explicação de como o editor lida com linhas pontilhadas ao adicionar novos dispositivos à proposição.
- Exemplo com MPV 1176/23.

## Dicas e Boas Práticas
- Dicas para evitar erros comuns ao trabalhar com linhas pontilhadas.
- Recomendações para assegurar a precisão na edição de emendas.

## Conclusão
- Resumo dos pontos chave abordados no tutorial.
- Encorajamento para prática e exploração das funcionalidades do editor.

## Encerramento
- Agradecimentos pela visualização.
- Incentivo para feedback e sugestões.

**Comment by arthurcordeiro** [comment]
[00:00] Introdução:
"Bem-vindo ao tutorial sobre o uso de linhas pontilhadas ao colar texto no editor de emendas. Neste vídeo, exploraremos diferentes cenários para entender melhor como o editor lida com essas linhas."

[00:30] Caso 1 - Adicionando Dispositivos a uma Norma Alterada:
"Ao colar um texto dentro da alteração da MPV 1199/23, as linhas pontilhadas serão preservadas exatamente como no dispositivo original."

Exemplo de texto a ser colado:
"Art. 3º ...............................................
.......................
§ 2º Constituem-se recursos próprios..."

[01:00] Caso 2 - Alterando Dispositivos Existentes:
"Quando alteramos um dispositivo existente na proposição ou em uma alteração de norma, as linhas pontilhadas são tratadas como partes inalteradas do texto. O editor ignora estas linhas ao realizar mudanças."

Exemplo de texto a ser colado:
"Art. 7º ...............................................
§ 1º ...............................................
II – valor de até R$ 15.000,00..."

[01:30] Caso 2.1 - Supressão de Dispositivos:
"A ausência de linha pontilhada ao final de uma lista indica a supressão de dispositivos não presentes no texto colado. Desfazer essas supressões é possível manualmente se necessário."

Exemplo de texto a ser colado:
"Art. 8º Poderão ser incluídas no Desenrola Brasil - Faixa 1 as dívidas de natureza privada..."

[02:00] Caso 3 - Adicionando Dispositivos à Proposição:
"Ao adicionar novos dispositivos à proposição, o editor remove linhas pontilhadas e renumera os dispositivos adjacentes, considerando que novos dispositivos não devem conter linhas pontilhadas."

Exemplo de texto a ser colado:
"Art. 2º Texto do caput do novo artigo
......
§ 5º Texto do novo parágrafo"

[02:30] Dicas e Boas Práticas:
"Algumas dicas para trabalhar com linhas pontilhadas incluem revisar cuidadosamente o texto após a colagem e utilizar as funcionalidades de desfazer e refazer para ajustar conforme necessário."

[03:00] Conclusão:
"Esperamos que este tutorial tenha esclarecido como trabalhar com linhas pontilhadas no editor de emendas. Pratique e explore para se familiarizar com estas funcionalidades."

[03:30] Encerramento:
"Agradecemos por assistir a este tutorial. Seu feedback e sugestões são sempre bem-vindos!"

**Comment by arthurcordeiro** [comment]
https://www.youtube.com/watch?v=uYXsH-F-AQM
