### ISSUE TITLE
Alterar nome de funcionalidade na Landing Page

### ISSUE THREAD

**Issue by eurobertacs** [lexml/editor-emendas#180]
Durante a elaboração dos tutoriais em pdf, foi levantada o esclarecimento sobre o significado da funcionalidade Verificar emenda, indicado na seção **Principais funcionalidades** na Landing Page. 

Na reunião com o Fragomeni, foi solicitada a alteração do nome da funcionalidade **Verificar emenda** para **Visualizar emenda**.

Em anexo, a indicação da localização da funcionalidade na página.

![Image](https://user-images.githubusercontent.com/90227731/236707263-d2844b6a-e354-45fb-b17d-01331b0511d2.png)

**Comment by arthurcordeiro** [comment]
https://github.com/lexml/editor-emendas/commit/d62045aa8f1a9522b51bfbc85313b77d6436062d


![Image](https://github.com/lexml/editor-emendas/assets/1903603/72a1f2c8-5531-485b-9f54-b79534310ae5)
