### ISSUE TITLE
Consolidar resultado do teste de usabilidade

### ISSUE THREAD

**Issue by fragomeni** [lexml/editor-emendas#184]
Ver:
- https://github.com/lexml/editor-emendas/issues/159

**Comment by kailinerocha** [comment]
Entrega 11/05

Segue relatório de teste consolidado.

[Relatório geral - resultado consolidado.pdf](https://github.com/lexml/editor-emendas/files/11454974/Relatorio.geral.-.resultado.consolidado.pdf)

**Comment by kailinerocha** [comment]
Entrega 11/05

Segue documento com bugs encontrados durante aplicação dos testes de usabilidade.

[Bugs encontrados - teste de usabilidade.pdf](https://github.com/lexml/editor-emendas/files/11454997/Bugs.encontrados.-.teste.de.usabilidade.pdf)

**Comment by kailinerocha** [comment]
Entrega 11/05

Tabela com resultado consolidado.


[resultado.pdf](https://github.com/lexml/editor-emendas/files/11455004/resultado.pdf)
