### ISSUE TITLE
Adicionar tutoriais em PDF à landing page

### ISSUE THREAD

**Issue by fragomeni** [lexml/editor-emendas#188]
Depende de #187

**Comment by arthurcordeiro** [comment]
https://github.com/lexml/editor-emendas/commit/d30f311e92f9841e76696eb30ba6ae2fff6dcf65

![Image](https://github.com/lexml/editor-emendas/assets/1903603/5a8c48d8-026c-4981-8124-f01909077e46)

**Comment by marianabrandt** [comment]
Achei que ficou muito poluído esse "ver passo a passo" repetido em todos os itens. Acho que se colocar o link para os pdf em cada item, na imagem e no texto, já resolve (quando o cursor muda para o ícone de clicável, geralmente as pessoas clicam). 

Ou mudar o título da seção de "Funcionalidades" para "Veja o passo a passo das funcionalidades" e deixar clicável na imagem e no texto
