### ISSUE TITLE
Apresentar na interface o tipo da emenda em edição "Padrão" ou "Dispositivos onde couber"

### ISSUE THREAD

**Issue by fragomeni** [lexml/editor-emendas#20]

**Comment by arthurcordeiro** [comment]
https://github.com/lexml/editor-emendas/commit/31d9cc890ed55b0dc09a1c9e66403c4f8a9ad02b

![Image](https://user-images.githubusercontent.com/1903603/187689954-e8d21579-9998-48b5-bc51-27a10d79c9b0.png)

**Comment by arthurcordeiro** [comment]
https://github.com/lexml/editor-emendas/commit/58e8def179c04b48f1bfce58072d45be72f65420

**Comment by fragomeni** [comment]
Deve ser adicionado um label depois da identificação da MPV informando "Onde couber" e tooltip "Emenda de dispositivos onde couber" quando estiver sendo editada uma emenda desse tipo.

**Comment by arthurcordeiro** [comment]
https://github.com/lexml/editor-emendas/commit/d66a11f183e76a4eabd89dd3d2faac3a235d736c

https://github.com/lexml/editor-emendas/commit/5241a4cad0c5bca34827c4a4ddd07a29a00b2b86
