### ISSUE TITLE
Especificar requisitos da emenda de texto livre

### ISSUE THREAD

**Issue by fragomeni** [lexml/editor-emendas#200]
### Introdução

A "emenda de texto livre" é um novo tipo de emenda que permite o usuário escrever uma emenda em forma de texto livre, de forma análoga à prática atual de elaboração de emendas no Word.

Este tipo de emenda deve ser utilizado como exceção nos casos não atendidos pelo editor de emendas. Alguns desses casos já são conhecidos e serão atendidos no futuro com a evolução do editor, entretanto, podem ocorrer casos ainda não previstos.

A elaboração de emendas de texto livre deve ser fortemente desencorajada no caso em que a emenda possa ser feita no formato estruturado.

Os casos conhecidos ainda não atendidos pelo editor são:
- Alteração de expressão em todo o texto (onde lê-se xxx, leia-se yyy);
- Emendamento ou adição de pena, penalidade etc.;
- Emendamento ou adição de especificação temática do dispositivo (usado para nome do tipo penal e outros);
- Emendamento ou adição de anexos;
- Alteração do texto da proposição e proposta de adição de dispositivos onde couber na mesma emenda (nesse caso é possível fazer a emenda posicionando os dispositivos onde couber);
- Alteração de norma que não segue a LC nº 95 de 98 (ex: norma com alíneas em parágrafos);
- Casos especiais de numeração de parte (PARTE GERAL, PARTE ESPECIAL e uso e numeral ordinal por extenso);
- Tabelas e imagens na justificativa ou no texto da proposição.

### Requisitos

A emenda de texto livre é um outro tipo de emenda, além da emenda padrão (intervenção direta no texto estruturado da proposição) e a emenda de dispositivo onde couber.

O usuário pode optar por este tipo de emenda selecionando "Outros tipos -> Texto livre" no menu.

Ao optar por este tipo de emenda deve ser apresentada uma popup:
- Informando que este tipo só deverá ser utilizado como uma exceção, em caso de impossibilidade de fazer a emenda de forma estruturada;
- [Avaliar] Pedindo ao usuário informar o motivo da utilização deste tipo de emenda permitindo ele selecionar um dos motivos conhecidos ou escrever o motivo no caso de motivos não previsto (outros);
  - [Avaliar] Este motivo será enviado para o e-mail editoremenda@camara.leg.br (ambientes de desenvolvimento não enviariam este e-mail).
- [Avaliar] Solicitando o contato do usuário.

Em vez de fazer intervenções no texto da proposição, o usuário escreverá diretamente o comando de emenda em um editor de texto rico, semelhante ao utilizado para a justificativa.

Funcionalidades necessárias ao editor de texto rico (para o comando de emenda e para a justificativa):
- Formatação básica de texto: negrito, itálico, sublinhado, sobrescrito e subscrito;
- Edição de listas numeradas ou não numeradas (bullets);
- Alinhamento de parágrafo (à esquerda, à direita, centralizado e justificado);
- Facilidades para formatação de texto normativo estruturado:
  - Possibilidade de estilo/classe para:
    - Artigo e dispositivos de artigo;
    - Agrupador de artigo (Título, Capítulo, Seção etc.);
    - Norma alterada (pode ser combinado com os acima);
    - Ementa
- Remover formatação;
- Remover estilo ou aplicar estilo padrão;
- Edição de tabelas;
- Inserção de imagens;

Deve ser possível anexar ou desanexar um arquivo PDF a ser usado como proposta de adição ou alteração de anexos da proposição.
- Inicialmente apenas um PDF.
- No caso de necessidade de adicionar mais de um anexo, o usuário deverá consolidar os vários anexos em um único PDF.

Continuarão sendo informadas separadamente a justificativa, data, autoria e opções de impressão, da mesma forma que para os demais tipos de emenda.

O PDF da emenda seguirá a mesma estrutura dos demais tipos de emenda, utilizando o comando de texto livre no lugar do comando de emenda e o anexo em seguida, se existir.

**Comment by fragomeni** [comment]
@marianabrandt, é apenas para facilitar a formatação.

**Comment by Emailrogs** [comment]
Excelente, Frago! 
Dúvida: No item "Alteração do texto da proposição e proposta de adição de dispositivos onde couber na mesma emenda (nesse caso é possível fazer a emenda posicionando os dispositivos onde couber)", não entendi bem o trecho que está entre parênteses.

**Comment by Emailrogs** [comment]
Concordo com os itens marcados com [Avaliar], sempre no sentido de desencorajar e onerar o uso da emenda de texto livre.

**Comment by fragomeni** [comment]
@Emailrogs, sobre a o trecho entre parêntesis, estava apenas explicando que, apesar de não ser possível alterar texto da MP e propor artigo onde couber na mesma emenda, isso não impede que o parlamentar faça uma emenda com o mesmo mérito com a diferença de, em vez de propor artigo onde couber, propor este artigo em alguma posição.
