### ISSUE TITLE
Criação de Blots para aceitar/recusar revisão nos dispositivos

### ISSUE THREAD

**Issue by fecocao** [lexml/editor-emendas#208]

**Comment by fecocao** [comment]
Criação dos blots no backend liberada para o Arthur atuar na estilização do html dos botões Aceitar e Recusar.

**Comment by arthurcordeiro** [comment]
Ajuste inicial dos botões de aceitar e recusar revisão
https://github.com/lexml/lexml-eta/commit/57dd94f7c317648851a79443af1a8b29020df70f

![Image](https://github.com/lexml/editor-emendas/assets/1903603/7084dd39-c98c-4f54-b281-fa3d156ccd46)

**Comment by fecocao** [comment]
Adicionada ações aos botões aceitar/rejeitar revisões em cada dispositivo.

**Comment by fecocao** [comment]
Ajuste no backend para chamada de ações aceitar/rejeitar revisões pelos botões rápidos. Estava fazendo múltiplas chamadas ao método.

**Comment by eurobertacs** [comment]
Na execução da issue https://github.com/lexml/lexml-eta/issues/653 do repositório lexml-eta foi contemplado os cenários de aceitar e recusar revisão dos dispositivos para o contexto de omissis.
