### ISSUE TITLE
Replicação de botão liga/desliga e contador de revisões na aba Justificativa

### ISSUE THREAD

**Issue by fecocao** [lexml/editor-emendas#209]

**Comment by fecocao** [comment]
![Image](https://github.com/lexml/editor-emendas/assets/25462574/7331d06a-29d0-49e1-8e02-ddb248ed896c)

**Comment by arthurcordeiro** [comment]
fix: ajusta toolbar após criação do webcomponent lexml-switch-revisao

https://github.com/lexml/lexml-eta/commit/36c17d3edcfb0fd808b10447d7d1acf04c81649e

![Image](https://github.com/lexml/editor-emendas/assets/1903603/67e4c88f-b095-4d9f-ad65-7169129b1f68)

![Image](https://github.com/lexml/editor-emendas/assets/1903603/80037956-3b83-4d85-8dab-91e9e3408801)
