### ISSUE TITLE
Aprimoramento do material de apoio (vídeo explicativo e “wiki” do projeto), inclusive sobre alteração de norma existente

### ISSUE THREAD

**Issue by fragomeni** [lexml/editor-emendas#215]
Proposta do consultor Marcos Pineschi

---

Seria importante incluir no vídeo explicativo no Youtube, bem como no “Wiki do projeto”, instruções sobre como fazer alterações em diversos artigos, ou em diversos diversos dispositivos de um mesmo artigo, abordando a criação e retirada da linha indicativa de omissis.

Como exemplo, o vídeo apresenta a alteração de um inciso I, mas poderia incluir, digamos, como seria o procedimento para a alteração de eventuais incisos II, IV e V (intercalados), ou a alteração de mais de um artigo na norma alterada.

De maneira geral, todos os vídeos e tutoriais do “wiki” do projeto poderiam ser mais detalhados, acrescentando exemplos de alterações mais complexas que, porventura, sejam necessárias.

**Comment by ceniravecchi** [comment]
Identificado que não é mais necessário.
Cancelado.
