### ISSUE TITLE
Apresentar popup de confirmação de elaboração de emenda de texto livre ao selecionar "Outros tipos -> Texto livre"

### ISSUE THREAD

**Issue by ceniravecchi** [lexml/editor-emendas#216]
Ao optar por este tipo de emenda deve ser apresentada uma popup:
- Informando que este tipo só deverá ser utilizado como uma exceção, em caso de impossibilidade de fazer a emenda de forma estruturada;
- Pedindo ao usuário informar o motivo da utilização deste tipo de emenda permitindo ele selecionar um dos motivos conhecidos ou escrever o motivo no caso de motivo não previsto (outros);
  - Este motivo será enviado para o e-mail editoremenda@camara.leg.br (ambientes de desenvolvimento não enviariam este e-mail).

Tarefa:

Apresentar popup de confirmação de elaboração de emenda de texto livre ao selecionar "Outros tipos -> Texto livre".

```
A emenda de texto livre deve ser utilizada apenas quando não for possível fazer a emenda no formato padrão do editor ou como emenda de dispositivo onde couber.

Selecione o motivo da opção pela emenda de texto livre:
O   Emendamento ou adição de pena, penalidade etc.
O   Emendamento ou adição de especificação temática do dispositivo (usado para nome do tipo penal e outros).
O   Alteração de anexo de MP de crédito extraordinário.
O   Emendamento ou adição de anexos.
O   Alteração do texto da proposição e proposta de adição de dispositivos onde couber na mesma emenda.
O   Alteração de norma que não segue a LC nº 95 de 98 (ex: norma com alíneas em parágrafos).
O   Casos especiais de numeração de parte (PARTE GERAL, PARTE ESPECIAL e uso de numeral ordinal por extenso);
O   Tabelas e imagens no texto da proposição.
O   Outro motivo: _____________________________

| Cancelar    | Continuar
```

- O botão cancelar apenas fecha a popup;
- Ao clicar em "continuar" deve ser validado o preenchimento do motivo ("Informe o motivo da opção pela emenda de texto livre"). Caso o usuário selecione "Outro motivo", ele deverá especificar o motivo na caixa de texto ("Escreva o motivo da opção pela emenda de texto livre").
- Ao continuar, enviar e-mail para editoremenda@camara.leg.br (modelo abaixo) e iniciar a elaboração de nova emenda de texto livre.
- Habilitar o envio de e-mail apenas em ambiente de produção.

```
Assunto ----
Nova emenda de texto livre

Texto ----
Nova emenda de texto livre

Motivo: <motivo selecionado, com especificação no caso de "outro motivo">
```

- Responsável: Dennys

**Comment by fragomeni** [comment]
Reprovado no teste:

Faltou a orientação de selecionar o motivo:

![Image](https://github.com/lexml/editor-emendas/assets/5323676/5cc44ef8-f584-4c36-ab31-a8e07c50083a)


**Fazer os seguintes ajustes**

1 - Sempre limpar os dados ao abrir a modal.

2 - Retire a informação "Dados inválidos" das mensagens de erro e deixe no lugar dela (em negrito) a mensagem específica.

![Image](https://github.com/lexml/editor-emendas/assets/5323676/d7cb4208-9486-48c9-816c-3267fbbedd8a)
