### ISSUE TITLE
Layout para apresentar prazo de emendamento e tempo de tramitação para MPs na listagem de MPs

### ISSUE THREAD

**Issue by fragomeni** [lexml/editor-emendas#217]
Na listagem:
- adicionar uma coluna "Prazo de emendas" com o valor "01/01/2000 (3 dias)" ou "encerrado"
- adicionar uma coluna "Tramitação" com o valor "9º dia" ou vazio (-)

**Comment by arthurcordeiro** [comment]
![Image](https://github.com/lexml/editor-emendas/assets/1903603/07ac813f-a0a8-4be9-a83a-87d1a2e576c1)

**Comment by arthurcordeiro** [comment]
Checar o critério dos dias de tramitação: dias corridos, dias úteis ou recessos?

**Comment by fragomeni** [comment]
@arthurcordeiro, são dias corridos.

**Comment by arthurcordeiro** [comment]
Veja se ficou bom assim, @fragomeni 
https://github.com/lexml/editor-emendas/commit/41d512df57ffe83d88cac2f99a3915fae4fba453

<img width="1150" alt="Captura de Tela 2023-08-24 às 13 33 31" src="https://github.com/lexml/editor-emendas/assets/1903603/e3d8205c-8ce8-4fb3-831b-99d0ed67b391">

**Comment by fragomeni** [comment]
Apresentar a coluna "Prazo de emendas" no padrão "01/01/2000 (3 dias)" ou "encerrado"

**Comment by arthurcordeiro** [comment]
https://github.com/lexml/editor-emendas/commit/de9262591eabd68391f8e6d85c8212c4e9d91a77

![Image](https://github.com/lexml/editor-emendas/assets/1903603/2f45e80f-b7c6-4e20-bd35-0b93a85543f7)
