### ISSUE TITLE
Criar botão que abre modal para informar nome e sigla de usuário

### ISSUE THREAD

**Issue by fragomeni** [lexml/editor-emendas#240]

**Comment by arthurcordeiro** [comment]
https://github.com/lexml/editor-emendas/commit/ae6bdf99aaa07e677ebd4be4badc45cf9e7e4a36

![Image](https://github.com/lexml/editor-emendas/assets/1903603/ef1924a7-14fc-41c8-b230-0169475edf19)
![Image](https://github.com/lexml/editor-emendas/assets/1903603/6f7bc09f-d482-4091-ba7a-1a24769a7b99)

**Comment by arthurcordeiro** [comment]
fix: ajusta textos no modal de nome de usuário
https://github.com/lexml/editor-emendas/commit/cdda00331a92395ae3ce955c27111ccf607a0db3

**Comment by robsonbarrosdf** [comment]
Concluído na branch develop
