### ISSUE TITLE
Visualização dos vídeos em tela cheia em largura de mobile não funciona

### ISSUE THREAD

**Issue by fragomeni** [lexml/editor-emendas#244]
Reportado pelo Rogério na homologação da Sprint 27

https://github.com/lexml/editor-emendas/assets/5323676/5628c57c-3907-4bae-bc35-6c783d96e106

___________________________________________
Conforme alinhado com o Fragomeni, 28/09/2023:
Grupo: 
Prioridade: Alta
Esforço: P

**Comment by arthurcordeiro** [comment]
[Frago] Problema relacionado ao fato de usarmos componentes acordeon para o mobile e tab para desktop
