### ISSUE TITLE
Comando de aceitar ou rejeitar revisões não está funcionando para uma Emenda com item

### ISSUE THREAD

**Issue by eurobertacs** [lexml/editor-emendas#256]
Ao abrir uma Emenda com itens criados e alterados e marcação de revisão ativado, os comandos de aceitar ou rejeitar todas as revisões não funciona.

Segue anexo do pdf e do vídeo.

[Emenda MPV 1175 2023-ações para item ao criar emenda para MP.pdf](https://github.com/lexml/editor-emendas/files/12241092/Emenda.MPV.1175.2023-acoes.para.item.ao.criar.emenda.para.MP.pdf)

https://user-images.githubusercontent.com/90227731/257842824-2cecf069-4c8f-4123-9684-3c53ec3b413e.mp4

**Comment by robsonbarrosdf** [comment]
Fazer teste na branch **develop** do lexml-eta com o arquivo Emenda MPV 1175 2023.emenda.json

**Comment by eurobertacs** [comment]
## Estimativa inicial para execução dos testes
3.75 USTs para 13 casos de testes e 1 plano de teste

## Transações e casos de testes
### <nome do serviço>
* **nome da Suíte de testes** 
  * nome do caso de testes da suíte
