### ISSUE TITLE
Parágrafo único não apresenta opções de controle de alterações ao alterar uma Emenda

### ISSUE THREAD

**Issue by eurobertacs** [lexml/editor-emendas#257]
A ação ocorreu quando um artigo novo é criado e, em seguida, é adicionado um parágrafo único.

Em anexos o arquivo pdf e o vídeo.

[Emenda MPV 1176 2023-ações para artigo ao criar emenda para MP.pdf](https://github.com/lexml/editor-emendas/files/12241449/Emenda.MPV.1176.2023-acoes.para.artigo.ao.criar.emenda.para.MP.pdf)

https://github.com/lexml/editor-emendas/assets/90227731/c4fdb871-96d1-420c-bcf2-aa5749f35529

**Comment by robsonbarrosdf** [comment]
Atualmente, em revisões criadas por inclusão de dispositivo, apenas o primeiro "dispositivo pai" adicionado possui as opções de aceitar ou rejeitar a revisão. Demais dispositivos subordinados fazem parte do mesmo "grupo" de revisão.

No exemplo em questão, como o artigo já está associado a uma revisão de inclusão de dispositivo, qualquer dispositivo subordinado (no caso, o parágrafo) faz parte do mesmo grupo de revisão.
