### ISSUE TITLE
Emendas de norma alterada não exibem as alterações nos dispositivos

### ISSUE THREAD

**Issue by eurobertacs** [lexml/editor-emendas#261]
O comportamento ocorreu para emendas em que os dispositivos parágrafo, inciso, alínea e item foram criados para verificar a exibição das marcas de alteração no pdf.

Em anexo, os arquivos pdfs.

[Emenda MPV 1171 2023-ações para item de norma alterada ao criar emenda.pdf](https://github.com/lexml/editor-emendas/files/12261389/Emenda.MPV.1171.2023-acoes.para.item.de.norma.alterada.ao.criar.emenda.pdf)
[Emenda MPV 1171 2023-ações para alínea de norma alterada ao criar emenda.pdf](https://github.com/lexml/editor-emendas/files/12261390/Emenda.MPV.1171.2023-acoes.para.alinea.de.norma.alterada.ao.criar.emenda.pdf)
[Emenda MPV 1171 2023-ações para inciso de norma alterada ao criar emenda.pdf](https://github.com/lexml/editor-emendas/files/12261392/Emenda.MPV.1171.2023-acoes.para.inciso.de.norma.alterada.ao.criar.emenda.pdf)
[Emenda MPV 1171 2023-ações para parágrafo de norma alterada ao criar emenda.pdf](https://github.com/lexml/editor-emendas/files/12261391/Emenda.MPV.1171.2023-acoes.para.paragrafo.de.norma.alterada.ao.criar.emenda.pdf)

https://github.com/lexml/editor-emendas/assets/90227731/42c63ff6-d2cb-4986-ac8d-2328cc31c525

**Comment by robsonbarrosdf** [comment]
Corrigido na branch develop do projeto (lexml-eta)
O componente será atualizado futuramente no projeto "editor de emendas"
