### ISSUE TITLE
Ignorar mensagem "NotAllowedError" quando usuário cancela salvamento

### ISSUE THREAD

**Issue by fragomeni** [lexml/editor-emendas#269]
1. Abra uma emenda salva.
2. Faça qualquer alteração.
3. Comande salvar
4. O Chrome vai apresentar a mensagem abaixo

![Image](https://github.com/lexml/editor-emendas/assets/5323676/7d6798b6-80ce-4933-b4f6-f3f09eb8a2e6)

5. Clique em cancelar
6. Será apresentada a seguinte mensagem

![Image](https://github.com/lexml/editor-emendas/assets/5323676/9d40620b-8a4d-49b2-b17a-0a68f3455e3a)

Essa mensagem deve ser ignorada e não apresentada ao usuário (filtra mensagem por "NotAllowedError".

Fazer no branch de release.

**Comment by robsonbarrosdf** [comment]
Resolvido na branch "release/0.10.0" e feito merge para branch "develop"
