### ISSUE TITLE
Criar página com iframe para quadro de emendas com cabeçalho do Congresso Nacional

### ISSUE THREAD

**Issue by fragomeni** [lexml/editor-emendas#270]
Criar página quadro-emendas.html no nível do index.html que deve apresentar o quadro de emendas em um iframe ocupando toda a página, com rolagem automática.

Todos os parâmetros de query recebidos por exta página devem ser repassados para o quadro de emendas e deve ser informado um parâmetro a mais, solicitando a apresentação da identidade visual do portal do Congresso Nacional.

Este outro parâmetro deve ser ser combinado com a equipe do quadro de emendas.

Utilizar javascript padrão sem necessidade de compilação typescript.

Serão utilizadas as URLs exemplificadas abaixo:

**Página inicial do quadro de emendas**
https://www6ghml.senado.leg.br/editor-emendas/quadro-emendas.html

**Quadro de emendas da MPV 1176/2023**
https://www6ghml.senado.leg.br/editor-emendas/quadro-emendas.html?sigla=MPV&numero=01176&ano=2023

Alterar as chamadas ao quadro de emendas feitas pelo editor de emendas para utilizar esta página.

**Comment by fragomeni** [comment]
Criar página quadro-emendas.html no nível do index.html que deve apresentar o quadro de emendas em um iframe ocupando toda a página, com rolagem automática.

Todos os parâmetros de query recebidos por exta página devem ser repassados para o quadro de emendas e deve ser informado um parâmetro a mais, solicitando a apresentação da identidade visual do portal do Congresso Nacional.

Este outro parâmetro deve ser ser combinado com a equipe do quadro de emendas.

Utilizar javascript padrão sem necessidade de compilação typescript.

Serão utilizadas as URLs exemplificadas abaixo:

**Página inicial do quadro de emendas**
https://www6ghml.senado.leg.br/editor-emendas/quadro-emendas.html

**Quadro de emendas da MPV 1176/2023**
https://www6ghml.senado.leg.br/editor-emendas/quadro-emendas.html?sigla=MPV&numero=01176&ano=2023

Alterar as chamadas ao quadro de emendas feitas pelo editor de emendas para utilizar esta página.

**Comment by arthurcordeiro** [comment]
https://github.com/lexml/editor-emendas/commit/319f7eaf0951e6bb9f9cdeb2ee4cadc0500cbbde

Criado também uma mensagem com a altura e largura da página do quadro de emendas para a página hospedeira redimensionar o iframe de acordo

![Image](https://github.com/lexml/editor-emendas/assets/1903603/59e531fb-99a8-4abd-9c3c-bf6e6cfac088)
