### ISSUE TITLE
Quando o usuário utiliza a omissão do texto do dispositivo de norma alterada, a janela de diferença de textos não estava responsivo

### ISSUE THREAD

**Issue by eurobertacs** [lexml/editor-emendas#271]
O erro ocorreu em qualquer dispositivo de norma alterada.

Segue vídeo:

https://github.com/lexml/editor-emendas/assets/90227731/826cee49-fafb-4958-9337-32e998959c24

**Comment by fecocao** [comment]
Correção no commit https://github.com/lexml/lexml-eta/commit/a5adbd1cb1b6c46e8fb2159f07ffa7892fdcfa58 na develop


![Image](https://github.com/lexml/editor-emendas/assets/25462574/04b53736-38da-4786-a670-98c695c78afd)
