### ISSUE TITLE
Layout para apresentar prazo de emendamento e tempo de tramitação para MPs durante a edição da emenda

### ISSUE THREAD

**Issue by fragomeni** [lexml/editor-emendas#277]
Mesmas informações do issue #217, mas na página de edição da emenda.
___________________________________________
Conforme alinhado com o Fragomeni, 28/09/2023:
Grupo: 
Prioridade: Baixa
Esforço: P

**Comment by arthurcordeiro** [comment]
Colocar um icone de relógio com tag

**Comment by arthurcordeiro** [comment]
https://github.com/lexml/editor-emendas/commit/41d31f8a46fc1949390089275a97932c75f03d29

![Image](https://github.com/lexml/editor-emendas/assets/1903603/ad01aaec-5024-4e48-908d-aa0de8ec43f7)
