### ISSUE TITLE
Página do quadro de emendas aparece em branco

### ISSUE THREAD

**Issue by robsonbarrosdf** [lexml/editor-emendas#304]
Página do quadro de emendas aparece em branco (ver imagem) quando acessada a partir do editor de emendas.

Obs: aconteceu durante uso da aplicação por Daniel Shim (CD) e Marcos Fragomeni (SF). Contudo ainda não foi possível identificar como provocar o erro intencionalmente.

![Image](https://github.com/lexml/editor-emendas/assets/37158063/874dc7fd-3bfe-495a-bf87-b53eacae587e)

**Comment by arthurcordeiro** [comment]
fix: trata retorno de altura do iframe no quadro de emendas, que aparece em branco aleatório 
https://github.com/lexml/editor-emendas/commit/5db3722e4a01010a6e12491fde3bc0c67b9a1a46
