### ISSUE TITLE
Ao abrir uma emenda salva (pdf) o botão salvar já vem habilitado

### ISSUE THREAD

**Issue by fecocao** [lexml/editor-emendas#309]
Botão salvar já está sendo habilitado mesmo sem nenhuma alteração ao abrir uma emenda.

![Image](https://github.com/lexml/editor-emendas/assets/25462574/263cadf7-76c5-40db-bab0-a7f3eb58d9e2)

**Comment by fecocao** [comment]
resolvido no commit https://github.com/lexml/editor-emendas/commit/81082029d9f453e2cae1b2a8ce41aa81880f3c2e

**Comment by fragomeni** [comment]
@fecocao, o botão permanece habilitado. Pode ser algo novo após a adição de várias outras funcionalidades.

**Comment by fecocao** [comment]
fix: desconsidera pendenciasPreenchimento como alterações na emenda para não ocorrerem erros ao abrir a emenda e indicarem diferenças errôneas: https://github.com/lexml/editor-emendas/commit/e0e1e4b673bcd4aae0a162679cdc12957b909c10
