### ISSUE TITLE
Acrescentar opção "Substituição de termo" no modal de nova emenda sem texto disponível

### ISSUE THREAD

**Issue by robsonbarrosdf** [lexml/editor-emendas#312]
- Acrescentar a opção "Substituição de termo" no modal exibido quando a proposição não possui texto estruturado (ver imagem abaixo)

- Alterar o texto das outras opções para "Onde couber" e "Texto livre"

**As opções devem ficar na seguinte ordem: Onde couber, Substituição de termo, Termo livre**

![Image](https://github.com/lexml/editor-emendas/assets/37158063/8bfad440-3d5e-49ab-9ec0-caf360654bd9)

**Comment by fecocao** [comment]
Implementado na branch feat/substituicao-termo-sem-articulacao
