### ISSUE TITLE
Sugestões do Rogério a respeito da modal de orientações

### ISSUE THREAD

**Issue by robsonbarrosdf** [lexml/editor-emendas#319]
Sugestões do Rogério a respeito da modal de orientações (#276):

_- **Sugestão**: Orientações 1/8: Substituir  “Número” por “número”_
_- **Sugestão**: Orientações 1/8: Substituir “Informações da Emenda” por “Emenda” (para ficar coerente com o que aparece na imagem ao lado do texto._ 
_- **Sugestão**: Orientações 1/8: Substituir “Mantenha-se informado com a versão atual do aplicativo” por “Mantenha-se informado sobre a versão atual do aplicativo”._

_- **Sugestão**: Orientações 2/8: Substituir “Indica quando...” por “Aparece quando...”_
_- **Sugestão**: Orientações 2/8: No item “Menu e Usuário”, incluir imagem com seta ou número, a exemplo do item “Sinalizador do arquivo não salvo”_

_- **Sugestão**: Orientações 3/8: Substituir “Área de edição” por “Editor”. Isso para manter correspondência com o slide_ “Orientações 1/8”
_- **Sugestão**: Orientações 3/8: Substituir “Área com alertas de erros nas alterações realizadas” por “Área com alertas de erros, omissões ou sugestões referentes à emenda em elaboração”_
_- **Sugestão**: Orientações 3/8: Substituir “... modo de revisão. (Só aparecerá quando existirem revisões na emenda)” por “... modo de revisão (só aparecerá quando existirem revisões na emenda).”_
_- **Sugestão**: Orientações 3/8: Atualizar a imagem (incluir Destino)_

_- **Sugestão**: Orientações 4/8: Substituir “Painel de Informações” por “Informações”. Isso para manter correspondência com o slide “Orientações 1/8”_
_- **Sugestão**: Orientações 4/8: Substituir “... Emenda lhe oferece”  por “.. Emenda oferece”_ 
_- **Sugestão**: Orientações 4/8: Substituir “Indicações precisas sobre ações sugeridas para a emenda.” por “Conteúdo da emenda em elaboração, com avisos e sugestões de melhorias._
_- **Sugestão**: Orientações 4/8: Substituir “Sugestões do que você pode fazer com o dispositivo selecionado.” para “Sugestões de ações disponíveis para o dispositivo selecionado”_

**Comment by arthurcordeiro** [comment]
fix: altera modal de orientações segundo sugestões do Rogério:

https://github.com/lexml/editor-emendas/commit/9b8d80c55575f494bce2ff39cf31ff3cfe4a6f1b
