### ISSUE TITLE
Retirar tags html da ementa apresentada no topo da tela

### ISSUE THREAD

**Issue by fragomeni** [lexml/editor-emendas#32]
![image](https://user-images.githubusercontent.com/5323676/188006948-a6f6d53e-6f02-491f-aae2-d48224084d5d.png)

**Comment by fragomeni** [comment]
Os links continuam aparecendo.



![Image](https://user-images.githubusercontent.com/5323676/190712161-b7a74a73-c015-4203-9a4c-37872f3c2ccc.png)

**Comment by jholanda** [comment]
![Image](https://user-images.githubusercontent.com/1719064/191141200-83008175-9201-4390-bf4e-8af0ce4a3081.png)
