### ISSUE TITLE
Modal do sufixo de posicionamento não aparece se o modo de edição for emenda de texto livre ou de substituição de termo

### ISSUE THREAD

**Issue by robsonbarrosdf** [lexml/editor-emendas#321]
A modal com explicação do "Sufixo de posicionamento" não aparece quando o tipo de emenda em edição é emenda de texto livre ou emenda de substituição de termo.

Para testar:
- Criar nova emenda de texto livre (ou de substituição de termo)
- Selecionar no menu **Ajuda** a opção **Substituição de termo**

![Image](https://github.com/lexml/editor-emendas/assets/37158063/0be2c181-c460-4c03-a388-68dc24ec09db)

**Comment by fecocao** [comment]
Resolvidos nos commits https://github.com/lexml/lexml-eta/commit/1b1e1dc4ae5fd34b2da64d3a361d78c6084ad355 e https://github.com/lexml/editor-emendas/commit/e43e5b0f43abe04614331d1299d85cd0cdb5009e
