### ISSUE TITLE
Remover do índice do Google as referências diretas de MPVs (robots.txt)

### ISSUE THREAD

**Issue by arthurcordeiro** [lexml/editor-emendas#325]
![Image](https://github.com/lexml/editor-emendas/assets/1903603/186f7bb2-ab96-4c09-acc5-cba82b05bd2c)

**Comment by arthurcordeiro** [comment]
Remove do índice do Google as referências diretas de MPVs (robots.txt)
https://github.com/lexml/editor-emendas/commit/27e54435f91512d1ccf74e5ca6c367c5facfee58

**Comment by ceniravecchi** [comment]
A solução funcionou. 
O google continua indexando os links de nova emenda.
Será aberta outra issue para tentar resolver o problema utilizando a "metatag HTML".
