### ISSUE TITLE
Criar efeito hover nos links do menu

### ISSUE THREAD

**Issue by fragomeni** [lexml/editor-emendas#33]
É estranho passar o mouse sobre o menu e a opção apontada não mudar em nada a sua visualização. Veja que há o hover no segundo nível do menu e nos botões das popups.

![image](https://user-images.githubusercontent.com/5323676/188008201-cb2e0539-7dc7-4cf8-900a-285df0b1acd9.png)

**Comment by arthurcordeiro** [comment]
https://github.com/lexml/editor-emendas/commit/9ee1b421464bb1bd16a8dbc48301937f1f996aa9
