### ISSUE TITLE
Adicionar vídeo 3 (colar com omissis) à modal de vídeos de ajuda

### ISSUE THREAD

**Issue by fragomeni** [lexml/editor-emendas#333]

**Comment by arthurcordeiro** [comment]
feat: adiciona vídeo colar com omissis à modal de vídeos de ajuda
https://github.com/lexml/editor-emendas/commit/ba6fad1ec150a9bf3733fa702e89d4d0d0cf997a

![Image](https://github.com/lexml/editor-emendas/assets/1903603/8db5b6a0-b5b6-4e5f-a06c-fca6d101677b)
