### ISSUE TITLE
PDF não aparece embutido no android

### ISSUE THREAD

**Issue by ceniravecchi** [lexml/editor-emendas#345]
https://github.com/lexml/editor-emendas/issues/151

![image](https://github.com/lexml/editor-emendas/assets/124091700/b476139e-30c4-4cc2-8aef-fe3a0c95b303)

**Comment by fecocao** [comment]
Adicionado biblioteca PDFJS ao projeto para visualizar as emendas. 

Desenvolvido na branch feat/pdfjs no editor-emendas.

@arthurcordeiro  resolver os scrools sendo triplicados no visualizador de forma errônea:


![Image](https://github.com/lexml/editor-emendas/assets/25462574/9f638a28-e33e-4bed-a173-b9d206053598)

**Comment by arthurcordeiro** [comment]
feat: define largura modal 100% no mobile
https://github.com/lexml/editor-emendas/commit/dc6c8fffa9a4b3c48c76cab8c498fed0f64312fb

<img src="https://github.com/lexml/editor-emendas/assets/1903603/a4ef9b42-d471-459d-b923-c71271020250)" alt="Descrição da Imagem" width="480px" />
