### ISSUE TITLE
Utilizar apenas interface de accordion para vídeos tutoriais 1.5.1

### ISSUE THREAD

**Issue by fragomeni** [lexml/editor-emendas#346]
Corrige bug de vídeo em full screen em ponto de quebra mobile.

**Comment by arthurcordeiro** [comment]
fix: utiliza apenas accordion para vídeos tutoriais 1.5.1
https://github.com/lexml/editor-emendas/commit/4b525740ce877e156877c8be6f284e7a8bf6cb44



![Image](https://github.com/lexml/editor-emendas/assets/1903603/115e03a0-cdac-4cb3-b92a-dbe91d407ab8)
