### ISSUE TITLE
Utilizar 100% da largura da popup na listagem de proposições mesmo que as ementas sejam pequenas

### ISSUE THREAD

**Issue by fragomeni** [lexml/editor-emendas#35]
![image](https://user-images.githubusercontent.com/5323676/188230457-26715357-7b1b-4795-a942-cc0dae4d82b7.png)

**Comment by arthurcordeiro** [comment]
https://github.com/lexml/editor-emendas/commit/77277d620851638d49f081cff1f961469d7f1132

![Image](https://user-images.githubusercontent.com/1903603/191090257-b5a94038-7c26-4565-bfdb-8dc5f70c599b.png)
