### ISSUE TITLE
Criar componente de loading e aplicar no nova emenda, abrir emenda e visualizar

### ISSUE THREAD

**Issue by fragomeni** [lexml/editor-emendas#45]

**Comment by arthurcordeiro** [comment]
@fragomeni, fiz pra nova e abrir emenda. O visualizar não consegui achar o ponto após o carregamento do PDF e também não consegui criar um componente.

![Image](https://user-images.githubusercontent.com/1903603/190224249-28951460-b9ac-4afe-82d0-08cb72d1285b.png)

https://github.com/lexml/editor-emendas/commit/4fc15d5dd7ace7ac80162828b1fc47d71275f8d2
