### ISSUE TITLE
Google analytics

### ISSUE THREAD

**Issue by fragomeni** [lexml/editor-emendas#51]

**Comment by arthurcordeiro** [comment]
https://github.com/lexml/editor-emendas/commit/a07847199313ff056f7e33675d8a4d0cc348b422

Instalado snippet do google analytics de conta de teste com os administradores abaixo:

![Image](https://user-images.githubusercontent.com/1903603/190475543-7684cdc9-5148-48a7-b174-cbb8df0bf675.png)

https://analytics.google.com/analytics/web/#/p331784761/reports/intelligenthome

![Image](https://user-images.githubusercontent.com/1903603/190474482-ba50bb4b-1723-45ab-bccc-a3bfe7903939.png)
