### ISSUE TITLE
Tratar caso de MPV sem texto disponível na listagem de MPV

### ISSUE THREAD

**Issue by fragomeni** [lexml/editor-emendas#56]
Nem todas MPVs têm o texto disponível para emendamento no formato LexML. É o caso de MPVs anteriores a 2020 e algumas de 2020.

Para MPVs que não possuem texto disponível, deve ser informado para usuário na listagem de proposições que o texto não está disponível e o usuário não deverá poder selecionar esta MPV para emendar.

MPVs que não têm o texto disponível não possuem o atributo "idSdlegDocumentoItemDigital" no json que vem do serviço de proposições.

**Comment by arthurcordeiro** [comment]
![Image](https://user-images.githubusercontent.com/1903603/190006837-4a703e5f-1d92-4933-829c-b6c44ce98459.png)

https://github.com/lexml/editor-emendas/commit/c5e9b6b2a42644cec87b66a5ddfac46b0ce27797

**Comment by arthurcordeiro** [comment]
feat: Adiciona badge "Texto indisponível" antes da ementa das MPVs antigas

![Image](https://user-images.githubusercontent.com/1903603/190012061-83e4cef7-44e8-41d4-8edf-be8f0ccbd1f5.png)

https://github.com/lexml/editor-emendas/commit/8e03bf17621ff22a926a68e068467af71ec0090d
