### ISSUE TITLE
Já abrir a janela de seleção do texto para emendamento com as MPVs do ano corrente.

### ISSUE THREAD

**Issue by fragomeni** [lexml/editor-emendas#69]
Da primeira vez que for aberta, já fazer a pesquisa. As MPVs passíveis de emendamento, em geral, estão entre as mais recentes.

**Comment by arthurcordeiro** [comment]
https://github.com/lexml/editor-emendas/commit/aa50a7fe76113a1b1e2d5cd3599d6b6036573ced
