### ISSUE TITLE
Trocar alerts por toasts nas mensagens de tratamento de erro de acesso a serviços

### ISSUE THREAD

**Issue by fragomeni** [lexml/editor-emendas#71]
Relacionado a #59.

Podem ser toasts ou outra solução que você achar melhor.

Verificar com @jholanda os pontos de tratamento de erro e como testar.

**Comment by arthurcordeiro** [comment]
https://github.com/lexml/editor-emendas/commit/7227f51a64c31c8faff4f401ea077ba94c00ea48

https://github.com/lexml/editor-emendas/commit/167c59074da98c5b77f6a8d33255088af2847cac

![Image](https://user-images.githubusercontent.com/1903603/191565452-4b10e1ed-dd46-4a8a-ae85-95e3cddbdfdc.png)
