### ISSUE TITLE
Apresentar nome do arquivo na barra superior

### ISSUE THREAD

**Issue by fragomeni** [lexml/editor-emendas#75]
Verificar com o @jholanda como obter o nome do arquivo.

![image](https://user-images.githubusercontent.com/5323676/191366041-8ddd7a0b-e99a-4ed9-8515-8b34eb412597.png)

**Comment by jholanda** [comment]
Existe um método getFilename() no edit-app.

**Comment by arthurcordeiro** [comment]
feat: Apresenta nome do arquivo na barra superior e trata nome do arquivo sugerido no salvar como

https://github.com/lexml/editor-emendas/commit/2e823b6145ba45a6e59326a087cd08f08d2ec1f4

![Image](https://user-images.githubusercontent.com/1903603/192315272-ef31e0ed-b3e3-43ed-9473-c5041464ba9e.png)

![Image](https://user-images.githubusercontent.com/1903603/192315368-5619cbef-33df-4e49-847e-3cd926b474ba.png)
