### ISSUE TITLE
Dar algum feedback ao usuário após salvar

### ISSUE THREAD

**Issue by fragomeni** [lexml/editor-emendas#76]
O salvar, após salvamento da primeira vez, não está apresentando nenhum comportamento visual que dê a entender que o procedimento funcionou.

**Comment by arthurcordeiro** [comment]
https://github.com/lexml/editor-emendas/commit/e2e9c61284202aace90ba538135014eac414856f

![Image](https://user-images.githubusercontent.com/1903603/192061086-545f09bd-e7be-4a5f-97f4-a1b128d33fca.png)
