### ISSUE TITLE
Edição e formatação de texto não está funcionando direito no Firefox

### ISSUE THREAD

**Issue by fragomeni** [lexml/editor-emendas#78]
Todos os dispositivos não originais ficam desformatados no Firefox e durante a digitação os espaços são perdidos.

![image](https://user-images.githubusercontent.com/5323676/191624666-5edbd7e7-5132-4306-aa0b-4bf01a0c8a9a.png)

**Comment by arthurcordeiro** [comment]
feat: adiciona firefox na lista de navegadores compatíveis
https://github.com/lexml/editor-emendas/commit/f06fc5241161099cf20a96c79eace410c6b2f2fe

fix: Corrige edição e formatação de texto no Firefox:
https://github.com/lexml/lexml-eta/commit/e1abf36e62dd2d33f849e436153d1815d2c3c2da

![Image](https://user-images.githubusercontent.com/1903603/202558160-f16e778f-0d24-42f3-8da3-dc0b29996b51.png)

**Comment by arthurcordeiro** [comment]
Corrigir os espaços em branco que não estão funcionando no firefox

**Comment by arthurcordeiro** [comment]
@fragomeni 

Esse problema não tem relação com estilo. Colei um texto com espaços e ficou OK. Ao digitar um espaço ele é colocado mas ao pressionar a próxima tecla o espaço é removido.

![Image](https://user-images.githubusercontent.com/1903603/203078198-0f750942-acbf-4733-873f-5d69ac430bce.png)

**Comment by arthurcordeiro** [comment]
fix: remove Firefox da lista de navegadores suportados até resolver essa issue.

https://github.com/lexml/editor-emendas/commit/f6595c7fd99a84d87fd4f2d9050980ec6b25e5d6

**Comment by arthurcordeiro** [comment]
Solução sugerida por @jholanda:
https://github.com/quilljs/quill/issues/1760

fix: espaço no fim do texto é apagado ao digitar nova tecla (Firefox)
https://github.com/lexml/lexml-eta/commit/41f007f37b958950d66ebf6f316f8822b4666333

fix: adiciona firefox na lista de navegadores suportados
https://github.com/lexml/editor-emendas/commit/399037c900ae070327c4e921b0dff45d39141aed
