### ISSUE TITLE
Ajustes na tela de seleção do texto para emendamento

### ISSUE THREAD

**Issue by fragomeni** [lexml/editor-emendas#87]
1) Limpar seleção após nova pesquisa
2) Limpar dados da MP selecionada na parte debaixo da tela após nova pesquisa.
3) Ordenar listagem em ordem da MP mais recente para a mais antiga.
4) Permitir seleção com clique duplo.
5) Remover zeros à esquerda do número da MP na listagem e na MP selecionada (debaixo da tela).

Os itens 1 e 2 resolvem bugs reportados por usuários.
----
Usuário: Quando clicar em +Nova, digitar o número da MPV e clicar no botão pesquisar, sugiro que a ementa do campo inferior também seja alterada.

Usuário: Tive alguns problemas ao buscar MPs novas. Não sei se é um erro ou eu não apertei o "enter" por aqui. Mesmo assim, percebi que quando colocamos uma MP na busca, ela aparece em amarelo, e quando clicamos em selecionar, ela continua a edição da antiga. (talvez um check-box com a necessidade de marcar a MP para selecionar ajude nisso)

**Comment by arthurcordeiro** [comment]
1. Limpar seleção após nova pesquisa e
https://github.com/lexml/editor-emendas/commit/ce4284cd0129df5826856818afe34b7f71d750b4

2. Limpar dados da MP selecionada na parte debaixo da tela após nova pesquisa.
https://github.com/lexml/editor-emendas/commit/ce4284cd0129df5826856818afe34b7f71d750b4

3. Ordenar listagem em ordem da MP mais recente para a mais antiga.
https://github.com/lexml/editor-emendas/commit/26a17ffd39cf3a71b9d2fc2d1817da0ed45667e9
![Image](https://user-images.githubusercontent.com/1903603/192624805-79bfca8b-8e86-4782-a338-58166c70d5fe.png)

4. Permitir seleção com clique duplo.
https://github.com/lexml/editor-emendas/commit/1040c28c7ad75a53408f3b79053481bdd2fd98e7

5. Remover zeros à esquerda do número da MP na listagem e na MP selecionada (debaixo da tela)
https://github.com/lexml/editor-emendas/commit/628add2ccb4e5025c28b310d44c5fefc71c3971e
![Image](https://user-images.githubusercontent.com/1903603/192624365-80291d8e-2a80-4b42-a3c1-840e4ff1fc8c.png)
