### ISSUE TITLE
Restringir uso do editor aos navegadores Chrome, Edge e Safari

### ISSUE THREAD

**Issue by fragomeni** [lexml/editor-emendas#88]
Na carga do editor, verificar se o navegador utilizado é Chrome, Edge ou Safari.

Caso não seja, apresentar mensagem informando quais são os navegadores suportados e orientando o usuário a acessar por outro navegador.

Não deve ser possível utilizar o editor em navegador não suportado.

Obs: Acredito que a implementação deva ser feita diretamente na página index.html

**Comment by arthurcordeiro** [comment]
https://github.com/lexml/editor-emendas/commit/1075fc07e2a1c69895a48b9d08fe1c85984a56e9

![Image](https://user-images.githubusercontent.com/1903603/194604941-9ccb578e-44e8-4f50-a338-b3b3b961dd36.png)
