### ISSUE TITLE
Rever layout da landing page

### ISSUE THREAD

**Issue by fragomeni** [lexml/editor-emendas#89]
Buscar forma de aumentar as chances do usuário ver os vídeos tutoriais e saber das restrições do editor.

**Comment by eurobertacs** [comment]
Fizemos uma reunião no dia 18/10/2022 para obter informações sobre o andamento dos trabalhos com a Ana e a definição das próximas ações.

Em função da licença que a Ana tirou por motivos pessoais, o trabalho será iniciado a partir de 19/10/2022.

As próximas ações são:
- Criação do grupo Whatsapp exclusivo para execução da demanda
- Criação do projeto no Figma para elaboração da Landing pages
- Agendamento de uma próxima reunião para 19/10/2022 após a daily do ALD 2.

**Comment by eurobertacs** [comment]
Arthur fez a criação dos recursos de comunicação e os insumos para demanda que são:

* Meet padrão no google: https://meet.google.com/avv-tvbi-nvj
* Projeto no Figma: https://www.figma.com/file/QkygudcIAlZ3nXshFgeNKv/Editor-de-Emendas?node-id=0%3A1
* Pasta de colaboração no Google Drive: https://drive.google.com/drive/folders/1ANX0uQtySoLv_B7SrwVRA4K-H_mpUNar

Na reunião do dia 19/10/2022, foi apresentado o Figma para os participantes e a Ana inicia os trabalhos de construção da Landing pages. A mesma informou que a próxima reunião será destinada para obtenção de esclarecimentos sobre o produto.

**Comment by arthurcordeiro** [comment]
Proposta inicial da Ana feita no Illustrator. Vou recriá-la no Figma para evoluirmos a proposta de forma colaborativa.

[Projeto_Emendas.pdf](https://github.com/lexml/editor-emendas/files/9838378/Projeto_Emendas.pdf)

**Comment by eurobertacs** [comment]
Na daily do dia 21/10/2022, Arthur apresentou a proposta da Ana para os participantes e foram obtidos feedbacks.

Após a daily, reunimos com a Ana para repassar a avaliação do time e acertar a entrega da primeira versão da Landing Page para 25/10/2022 (quinta-feira).

**Comment by eurobertacs** [comment]
[Projeto_Emendas.pdf](https://github.com/lexml/editor-emendas/files/9869696/Projeto_Emendas.pdf)

**Comment by eurobertacs** [comment]
Fiz o documento com as contribuições para Landing Page e repassei para o Arthur.

Segue anexo do documento.

[Contribuições para página bootstrap da Landing page.docx](https://github.com/lexml/editor-emendas/files/9872121/Contribuicoes.para.pagina.bootstrap.da.Landing.page.docx)

**Comment by eurobertacs** [comment]
No dia 27/10/2022, foram realizadas duas reuniões com o Arthur para esclarecer as contribuições repassadas em 25/10/2022. O documento foi atualizado para conter os links do tutorial e a inclusão das frases das funcionalidades que serão disponibilizadas em versões futuras. O documento está em anexo.

Foi realizada uma reunião com o time ALD 2 e Dileg onde o Arthur apresentou a Landing Pages.

A Dileg fez uma avaliação após a apresentação do Arthur e repassou o feedback. Eu e Arthur combinamos de analisar.

[Contribuições para página bootstrap da Landing page-27-10-2022.docx](https://github.com/lexml/editor-emendas/files/9928316/Contribuicoes.para.pagina.bootstrap.da.Landing.page-27-10-2022.docx)

**Comment by eurobertacs** [comment]
Nos dias 31/10/2022 e 01/11/2022, Mariana (Dileg) concedeu acesso para utilizar a ferramenta que contém as informações do feedback da Dileg sobre a Landing Page.

Arthur conseguiu visualizar e fez os ajustes.

**Comment by arthurcordeiro** [comment]
https://www.congressonacional.leg.br/editor-emendas/
