### ISSUE TITLE
Quando uma MPV é inexistente, o Editor não exibe mensagem

### ISSUE THREAD

**Issue by eurobertacs** [lexml/editor-emendas#91]
Segue anexos para visualização.

https://user-images.githubusercontent.com/90227731/193063651-3a0ee9e4-c1e3-4adf-a860-9a01da204ecf.mp4
https://user-images.githubusercontent.com/90227731/193063650-de93d072-b881-4d0d-b7b8-a9cad58c7638.mp4

**Comment by fragomeni** [comment]
O editor passou a não permitir a seleção de MP inexistente.
