### ISSUE TITLE
Quando o usuário realiza mais de uma pesquisa, a ementa da primeira proposição é mantida e não fica vazia

### ISSUE THREAD

**Issue by eurobertacs** [lexml/editor-emendas#92]
Em anexo, o vídeo para análise.

https://user-images.githubusercontent.com/90227731/193066196-56dbb195-a7d6-4e49-bb6b-b3f302fab5b7.mp4

**Comment by fragomeni** [comment]
Foi corrigido em alguma sprint passada.
